"use client";

import { useState, type ReactNode } from "react";
import { Droplets, ImageIcon, Pencil, Shapes, Soup, X } from "lucide-react";
import { AquariumRenderer } from "@/components/aquarium/aquarium-renderer";
import { Button } from "@/components/ui/button";
import { useSharedAquariumAction } from "@/features/friends/use-shared-aquariums";
import { shopProducts } from "@/lib/app-assets";
import type { FishView, SharedAquariumView } from "@/types/game";

type ShopMode = "backgrounds" | "decor" | null;

export function SharedAquariumModal({ aquarium, onClose }: { aquarium: SharedAquariumView; onClose: () => void }) {
  const action = useSharedAquariumAction();
  const [renameFish, setRenameFish] = useState<FishView | null>(null);
  const [name, setName] = useState("");
  const [shopMode, setShopMode] = useState<ShopMode>(null);
  const products = shopMode ? shopProducts.filter((product) => product.category === shopMode) : [];
  const openRename = (fish: FishView) => { setRenameFish(fish); setName(fish.name); };
  return <div data-app-modal="true" className="fixed inset-0 z-[70] grid place-items-end bg-slate-950/75 p-3 sm:place-items-center"><div className="glass max-h-[94dvh] w-full max-w-md space-y-3 overflow-y-auto rounded-3xl p-4"><div className="flex items-center justify-between"><div><div className="text-xl font-black">{aquarium.name}</div><div className="text-xs text-cyan-100/60">Вместе с {aquarium.friendName} · {aquarium.fish.length}/12 рыб</div></div><button type="button" aria-label="Закрыть общий аквариум" className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950/40" onClick={onClose}><X /></button></div>
    <div className="h-[48dvh] min-h-72 overflow-hidden rounded-2xl"><AquariumRenderer fish={aquarium.fish} className="h-full min-h-0 rounded-none" pollution={aquarium.pollution} backgroundId={aquarium.backgroundId} decor={aquarium.decor} /></div>
    <div className="grid grid-cols-4 gap-2"><Action icon={<Soup />} label="Корм" color="bg-amber-300" onClick={() => action.mutate({ aquariumId: aquarium.id, action: "feed" })} disabled={action.isPending} /><Action icon={<Droplets />} label="Чистка" color="bg-cyan-300" onClick={() => action.mutate({ aquariumId: aquarium.id, action: "clean" })} disabled={action.isPending} /><Action icon={<ImageIcon />} label="Фоны" color="bg-violet-300" onClick={() => setShopMode(shopMode === "backgrounds" ? null : "backgrounds")} /><Action icon={<Shapes />} label="Декор" color="bg-emerald-300" onClick={() => setShopMode(shopMode === "decor" ? null : "decor")} /></div>
    {shopMode ? <section className="space-y-2 rounded-2xl border border-cyan-100/12 bg-slate-950/35 p-3"><div className="font-black">{shopMode === "backgrounds" ? "Фоны общего аквариума" : "Декорации общего аквариума"}</div><p className="text-[11px] text-cyan-100/55">Купленное остаётся в этом общем аквариуме и видно рядом с некупленным.</p><div className="grid grid-cols-2 gap-2">{products.map((product) => { const owned = aquarium.ownedItemIds.includes(product.id); const active = shopMode === "backgrounds" ? aquarium.backgroundId === product.id : aquarium.decor.includes(product.id); return <button type="button" key={product.id} disabled={action.isPending} onClick={() => action.mutate({ aquariumId: aquarium.id, action: "customize", itemId: product.id })} className={`overflow-hidden rounded-2xl border text-left ${active ? "border-emerald-300 bg-emerald-300/12" : "border-cyan-100/12 bg-slate-950/40"}`}><img src={product.image} alt="" className="h-24 w-full object-cover" /><div className="space-y-1 p-2"><div className="truncate text-xs font-black">{product.title}</div><div className={`text-[10px] font-bold ${owned ? "text-emerald-200" : "text-amber-200"}`}>{active ? "Установлено" : owned ? shopMode === "decor" ? "Куплено · установить" : "Куплено · выбрать" : `${product.price} водорослей`}</div></div></button>; })}</div></section> : null}
    <section className="space-y-2"><div className="text-xs font-black text-cyan-100/70">Нажми на рыбку, чтобы изменить её имя</div><div className="grid grid-cols-2 gap-2">{aquarium.fish.map((fish) => <button type="button" key={fish.id} onClick={() => openRename(fish)} className="flex min-w-0 items-center gap-2 rounded-xl border border-cyan-100/10 bg-slate-950/30 p-2 text-left"><div className="min-w-0 flex-1"><div className="truncate text-sm font-black">{fish.name}</div><div className="truncate text-[10px] text-cyan-100/50">{fish.displayName}</div></div><Pencil className="h-4 w-4 shrink-0 text-cyan-200" /></button>)}</div></section>
    {action.error ? <p className="text-sm text-rose-200">{action.error.message}</p> : null}</div>
    {renameFish ? <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/80 p-4"><form className="glass w-full max-w-sm space-y-3 rounded-3xl p-4" onSubmit={(event) => { event.preventDefault(); action.mutate({ aquariumId: aquarium.id, action: "rename", fishId: renameFish.id, name }, { onSuccess: () => setRenameFish(null) }); }}><div><div className="text-lg font-black">Имя для {renameFish.displayName}</div><div className="text-xs text-cyan-100/55">Это имя будет одинаковым у вас обоих.</div></div><input autoFocus maxLength={18} value={name} onChange={(event) => setName(event.target.value)} className="h-12 w-full rounded-xl border border-cyan-100/15 bg-slate-950/55 px-3 font-bold outline-none focus:border-cyan-300" /><div className="grid grid-cols-2 gap-2"><Button type="button" className="bg-slate-700" onClick={() => setRenameFish(null)}>Отмена</Button><Button type="submit" disabled={action.isPending || name.trim().length < 2}>Сохранить</Button></div></form></div> : null}</div>;
}

function Action({ icon, label, color, onClick, disabled = false }: { icon: ReactNode; label: string; color: string; onClick: () => void; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className={`${color} flex min-w-0 flex-col items-center gap-1 rounded-2xl px-1 py-2 text-slate-950 disabled:opacity-50`}><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span><span className="text-[10px] font-black">{label}</span></button>; }
