ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "profileName" TEXT,
ADD COLUMN IF NOT EXISTS "profileBio" TEXT,
ADD COLUMN IF NOT EXISTS "profileAvatar" TEXT;

ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'MATCH_THREE_REWARD';
